### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by uloveqian2021** [Ephrem-ETH/E2E-KWS#1]
Hi, Nice Job, is there a paper on this project?

**Comment by Ephrem-ETH** [comment]
> Hi, Nice Job, is there a paper on this project

**Comment by Ephrem-ETH** [comment]
> Hi, Nice Job, is there a paper on this project?

Thank you. Yes. it is my thesis work too

**Comment by Ephrem-ETH** [comment]
> Hi, Nice Job, is there a paper on this project?

Thank you. Yes. it is my thesis work too

**Comment by Ephrem-ETH** [comment]
> Hi, Nice Job, is there a paper on this project?

Thank you. Yes( but ongoing). it is my thesis work too

**Comment by wangbq18** [comment]
> > Hi, Nice Job, is there a paper on this project?
> 
> Thank you. Yes. it is my thesis work too

could you share a link to the paper?

**Comment by Ephrem-ETH** [comment]
> 

https://ieeexplore.ieee.org/abstract/document/9746012

**Comment by wangbq18** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好!我已收到您的邮件！
